data:
    modality: "2D"
    # dataset: "Quadratic"
    dataset: "Gaussian2D"
    num_data: 1000
    dimension: 100
    hyp_len: 0.8 #Quadratic : 0.8
    hyp_gain: 1.0
    num_workers: 4

model:
    model_type: "AFNO2D"
    #n_modes: [100,]
    n_modes: [32, 32] 
    hidden_channels: 256
    in_channels: 3
    out_channels: 1
    lifting_channels: 256
    projection_channels: 256
    n_layers: 4
    norm: 'group_norm'
    preactivation: True
    skip: 'soft-gating'
    separable: True
    factorization: null
    rank: 1
    joint_factorization: True
    fixed_rank_modes: False
    implementation: 'factorized'
    ckpt_dir: "./exp/logs/quadratic_experiment/ckpt_step_20000.pth"
    # --- AFNO 고유 하이퍼파라미터 추가 ---
    num_blocks: 8
    sparsity_threshold: 0.01
    hidden_size_factor: 2   
    hard_thresholding_fraction: 1.0

diffusion:
    beta_schedule: "cosine"
    num_diffusion_timesteps: 1000

training:
    batch_size: 100
    n_epochs: 2000
    ckpt_store: 100
    val_freq: 100  # Validation frequency (every N steps)
    val_batch_size: 50 
    sobolev_weight: 1.0 # Sobolev weight 
    lambda_norm: 0.1 # normalize weight

sampling:
    batch_size: 1000
    clamp_threshold: 1000
    inference_steps:  500    

optim:
    lr: 0.00001
    grad_clip: 1.0

